version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres:latest
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - 5432:5432
  web:
    build: ./server
    command: python server.py
    volumes:
      - ./server:/server
    ports:
      - 5001:5000
    depends_on:
      - db
      - rabbitmq
  daemon:
    build: ./daemon
    command: python daemon.py
    volumes:
      - ./daemon:/daemon
    depends_on:
      - db
      - rabbitmq
  cache:
    image: redis:latest
    ports:
      - 6379:6379